FORMAT: 1A
HOST: http://

# Sports Club

A simple API allowing consumers to view polls and vote in them.

# Group Membership

## Members Collection [/members]

### List All Members [GET]

+ Response 200 (application/json)

        {
            "members": [
                {
                    "name" : "rod",
                    "membership_type" : "player"
                },
                {
                    "name" : "jayne",
                    "membership_type" : "member"
                },
                {
                    "name" : "fred",
                    "membership_type" : "player"
                }
            ]
        }

# Group Players

## Available Players [/members/available]

### List Available Players [GET]

+ Request (application/json)

    + Attributes
      + date: 22/07/2018 (string)

+ Response 200 (application/json)

        {
            "players": [
                {
                    "name" : "rod",
                    "positions" : [
                    "position" : "centre",
                    "position" : "winger",
                    "position" : "full_back"
                    ]
                },
                {
                    "name" : "brett",
                    "positions" : [
                        "position" : "prop",
                        "position" : "hooker"
                    ]
                },
                {
                    "name" : "fred",
                    "positions" : [
                        "position" : "winger"
                    ]
                }
            ]
        }

# Group Team

## Team Collection [/team/{team_name}]

### List Team Members [GET]

+ Parameters
    + team_name: 'development' (string)

+ Response 200 (application/json)
    
    + Attributes (array[TeamPlayerList])

    + Body

            {
                "team": [
                   {
                        "nickname" : "rod",
                        "prefered_position" : "centre",
                        "positions": [
                            "position" : "centre",
                            "position" : "winger",
                            "position" : "full_back"
                            ]
                   },
                   {
                        "nickname" : "brett",
                        "prefered_position" : "prop",
                        "positions" : [
                            "position" : "prop",
                            "position" : "hooker"
                            ]
                    },
                    {
                        "nickname" : "fred",
                        "prefered_position" : "winger",
                        "positions" : [
                            "position" : "winger"
                            ]
                    }
                ]
            }

# Group Player

## Player Collection [/player/{?member_id}]

### List Player Details [GET]

+ Parameters
    + member_id: 1 (number)

+ Response 200 (application/json)
    
    + Attributes (Member)

### Change Player Details [POST]

+ Response 200 (application/json)
    
    + Attributes (Member)

    + Body

            {
                  "firstname": "ben",
                  "lastname": "smith",
                  "nickname": "tiny",
                  "prefered_position": "hooker",
                  "positions": [
                        {
                            "positon": "hooker",
                            "position": "`tight_head_prop`"
                        }
                  ]
            }

## List Players Availability  [/player/availability]

### All Players Current Week Availability [GET]

+ Response 200 (application/json)
    
    + Attributes (Player)

## A Players Availability  [/player/{member_id}/availability]
+ Parameters
    + member_id: 1 (number)


# Group Coaches

## Coaches Collection [/coaches]
Information on the clubs coaches

### List Coaches Details [GET]

+ Response 200 (application/json)
    
    + Attributes (Coach)


# Data Structures

## Person (object)
+ firstname: ben (string) 
+ lastname: smith (string)

## MembershipType (object)
+ membership: player (enum[string])
  + member
  + player
  + vp

## Member (Person)
+ Include MembershipType

## Player (Person)
+ nickname: smithy (string)
+ `prefered_position`: hooker (string)
+ positions (array[Positions])

## Positions (object)
+ positon: hooker (enum[string])
  + prop
  + second_row
  + hooker
  + flanker
  + centre

## TeamPlayerList (object)
+ Team (object)
  + Include Player

## Teams (object)
+ team: first (enum[string])
  + first
  + second
  + development
  + vets
  + colts
  + under_7s
  + under_8s
  + under_9s
  + under_10s
  + under_11s
  + under_12s
  + under_13s
  + under_14s
  + under_15s
  + under_16s
  + vipers

## Coach (Person)
+ teams (array[Teams])
+ qualifications (array[CoachingQuals])

## CoachingQuals (object)
+ course: rugby_ready (enum[string])
  + scrum_factory
  + rugby_ready
  + level_2
  + level_3